KDTree.domain.orq ../data/sphere.6.ascii 2 ../data/sphere.queries > KDTree.domain.sphere.query_size.timings
KDTree.domain.orq ../data/sphere.6.ascii 4 ../data/sphere.queries >> KDTree.domain.sphere.query_size.timings
KDTree.domain.orq ../data/sphere.6.ascii 8 ../data/sphere.queries >> KDTree.domain.sphere.query_size.timings
KDTree.domain.orq ../data/sphere.6.ascii 16 ../data/sphere.queries >> KDTree.domain.sphere.query_size.timings
KDTree.domain.orq ../data/sphere.6.ascii 32 ../data/sphere.queries >> KDTree.domain.sphere.query_size.timings
KDTree.domain.orq ../data/sphere.6.ascii 64 ../data/sphere.queries >> KDTree.domain.sphere.query_size.timings
