KDTree.domain.orq ../data/uniform_random.6.ascii 2 random.queries > KDTree.domain.random.query_size.timings
KDTree.domain.orq ../data/uniform_random.6.ascii 4 random.queries >> KDTree.domain.random.query_size.timings
KDTree.domain.orq ../data/uniform_random.6.ascii 8 random.queries >> KDTree.domain.random.query_size.timings
KDTree.domain.orq ../data/uniform_random.6.ascii 16 random.queries >> KDTree.domain.random.query_size.timings
KDTree.domain.orq ../data/uniform_random.6.ascii 32 random.queries >> KDTree.domain.random.query_size.timings
KDTree.domain.orq ../data/uniform_random.6.ascii 64 random.queries >> KDTree.domain.random.query_size.timings
