SortRankProject.mesh ../data/uniform_random.3.ascii 0.232079 >> SortRankProject.random100.timings
SortRankProject.mesh ../data/uniform_random.4.ascii 0.107722 >> SortRankProject.random100.timings
SortRankProject.mesh ../data/uniform_random.5.ascii 0.05 >> SortRankProject.random100.timings
#SortRankProject.mesh ../data/uniform_random.6.ascii 0.0232079 >> SortRankProject.random100.timings
#SortRankProject.mesh ../data/uniform_random.7.ascii 0.0107722 >> SortRankProject.random100.timings
