"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

# Make pytz backwards compatible.
# I got this fix from
# http://mail.python.org/pipermail/pythonmac-sig/2008-June/020111.html
#import pytz
#pytz.zoneinfo = pytz.tzinfo
#pytz.zoneinfo.UTC = pytz.UTC

# setup_options['options']['py2app']['includes'].extend(['pytz.zoneinfo.UTC'])

APP = ['Cain.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
           'packages': ['numpy', 'matplotlib']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
