# -*- Makefile -*-

directories := $(dir $(shell ls */Makefile))

.PHONY: $(directories)
default: $(directories)
$(directories):
	$(MAKE) -C $@ $(MAKEFLAGS) $(MAKECMDGOALS)

clean: default
	$(RM) *~
distclean: clean
again: distclean
