# -*- python -*-

import os.path

import sys
sys.path.append('../../..')
from env import serial, openMP

# Compile.
sources = Glob('*.cc')
for source in sources:
    serial.Program(source)

openMP.Program('CellArrayNeighborsThreaded', openMP.Object('CellArrayNeighborsThreaded.o', 'CellArrayNeighbors.cc'))
