# -*- python -*-

import sys
sys.path.append('..')
from doxygen import doxygen

doxygen.Doxyfile('Doxyfile', ['../main.cfg', 'local.cfg'])
target = '../html/stochastic/index.html'
Default([target])
sources = Glob('../../stlib/stochastic/*.h') \
          + ['../ads/ads.tag', '../container/container.tag', '../ext/ext.tag',
             '../numerical/numerical.tag']
doxygen.Doxygen([target, 'stochastic.tag'], ['Doxyfile'] + sources)
Clean(target, ['../html/stochastic', 'stochastic.tag'])
