Placebo.mesh ../data/uniform_random.3.ascii 0.232079 100 >> Placebo.random100.timings
Placebo.mesh ../data/uniform_random.4.ascii 0.107722 100 >> Placebo.random100.timings
Placebo.mesh ../data/uniform_random.5.ascii 0.05 100 >> Placebo.random100.timings
Placebo.mesh ../data/uniform_random.6.ascii 0.0232079 100 >> Placebo.random100.timings
#Placebo.mesh ../data/uniform_random.7.ascii 0.0107722 100 >> Placebo.random100.timings
