Placebo.mesh ../data/uniform_random.2.ascii 0.232079 8 >> Placebo.random.timings
Placebo.mesh ../data/uniform_random.3.ascii 0.107722 9 >> Placebo.random.timings
Placebo.mesh ../data/uniform_random.4.ascii 0.05 10 >> Placebo.random.timings
Placebo.mesh ../data/uniform_random.5.ascii 0.0232079 10 >> Placebo.random.timings
Placebo.mesh ../data/uniform_random.6.ascii 0.0107722 10 >> Placebo.random.timings
#Placebo.mesh ../data/uniform_random.7.ascii 0.005 10 >> Placebo.random.timings
