Placebo.mesh ../data/chair.01.ascii 2 36 >> Placebo.chair.timings
Placebo.mesh ../data/chair.02.ascii 2 36 >> Placebo.chair.timings
Placebo.mesh ../data/chair.04.ascii 2 29 >> Placebo.chair.timings
Placebo.mesh ../data/chair.08.ascii 2 27 >> Placebo.chair.timings
Placebo.mesh ../data/chair.16.ascii 2 26 >> Placebo.chair.timings
Placebo.mesh ../data/chair.32.ascii 2 25 >> Placebo.chair.timings
#Placebo.mesh ../data/chair.64.ascii 2 >> Placebo.chair.timings
