# -*- python -*-

import sys
sys.path.append('..')
from env import serial

# Compile.
sources = Glob('*.cc')
for source in sources:
    serial.Program(source)

# Run.
targets = [str(x).split('.')[0] for x in sources]
for x in targets:
    serial.Run(source=x)

Import('errors')
errors.append(Glob('*.err'))
