# -*- python -*-

import sys
sys.path.append('../..')
from env import mpi

if mpi:
    # Compile.
    sources = Glob('*.cc')
    for source in sources:
        mpi.Program(source)

    # Run.
    targets = [str(x).split('.')[0] for x in sources]
    for x in targets:
        mpi.Run(source=x)

    Import('errors')
    errors.append(Glob('*.err'))
