# -*- python -*-

import sys
sys.path.append('..')
from doxygen import doxygen

doxygen.Doxyfile('Doxyfile', ['../main.cfg', 'local.cfg'])
target = '../html/mst/index.html'
Default([target])
sources = Glob('../../stlib/mst/*.h') + Glob('../../examples/mst/*.h') \
          + ['../ads/ads.tag', '../container/container.tag', '../geom/geom.tag',
             '../numerical/numerical.tag']
doxygen.Doxygen([target, 'mst.tag'], ['Doxyfile'] + sources)
Clean(target, ['../html/mst', 'mst.tag'])
