# -*- python -*-

import sys
sys.path.append('..')
from doxygen import doxygen

doxygen.Doxyfile('Doxyfile', ['../main.cfg', 'local.cfg'])
target = '../html/container/index.html'
Default([target])
sources = Glob('../../stlib/container/*.h')
doxygen.Doxygen([target, 'container.tag'], ['Doxyfile'] + sources)
Clean(target, ['../html/container', 'container.tag'])
