# -*- python -*-

import sys
sys.path.append('..')
from env import mpi

if mpi:
    # Compile.
    sources = Glob('*.cc')
    # Unless we are using MSVC, specify the libraries.
    if mpi['CC'] == 'cl':
        for source in sources:
            mpi.Program(source)
    else:
        for source in sources:
            #mpi.Program(source, LIBS=['boost_program_options'])
            mpi.Program(source)
