# -*- python -*-

import sys
sys.path.append('..')
from doxygen import doxygen

doxygen.Doxyfile('Doxyfile', ['../main.cfg', 'local.cfg'])
target = '../html/ads/index.html'
Default([target])
sources = Glob('../../stlib/ads/*.h') + Glob('../../stlib/ads/*/*.h')
doxygen.Doxygen([target, 'ads.tag'], ['Doxyfile'] + sources)
Clean(target, ['../html/ads', 'ads.tag'])
