# -*- python -*-

import sys
sys.path.append('../..')
from env import openMP

# Compile.
sources = Glob('*.cc')
for source in sources:
    openMP.Program(source)

# Run.
targets = [str(x).split('.')[0] for x in sources]
for x in targets:
    openMP.Run(source=x)

Import('errors')
errors.append(Glob('*.err'))
