# -*- python -*-

SConscript([str(x) for x in Glob('*/SConscript')])

import sys
sys.path.append('../..')
from env import serial

# Compile.
sources = Glob('*.cc')
for source in sources:
    serial.Program(source)
