KDTree.domain.mesh ../data/uniform_random.3.ascii 16 0.232079 >> KDTree.domain.random100.timings
KDTree.domain.mesh ../data/uniform_random.4.ascii 16 0.107722 >> KDTree.domain.random100.timings
KDTree.domain.mesh ../data/uniform_random.5.ascii 16 0.05 >> KDTree.domain.random100.timings
KDTree.domain.mesh ../data/uniform_random.6.ascii 16 0.0232079 >> KDTree.domain.random100.timings
#KDTree.domain.mesh ../data/uniform_random.7.ascii 16 0.0107722 >> KDTree.domain.random100.timings
