KDTree.domain.mesh ../../../../../../data/geom/orq/uniform_random.2.ascii 8 0.232079 >> KDTree.domain.txt
KDTree.domain.mesh ../../../../../../data/geom/orq/uniform_random.3.ascii 8 0.107722 >> KDTree.domain.txt
KDTree.domain.mesh ../../../../../../data/geom/orq/uniform_random.4.ascii 8 0.05 >> KDTree.domain.txt
KDTree.domain.mesh ../../../../../../data/geom/orq/uniform_random.5.ascii 8 0.0232079 >> KDTree.domain.txt
KDTree.domain.mesh ../../../../../../data/geom/orq/uniform_random.6.ascii 8 0.0107722 >> KDTree.domain.txt
#KDTree.domain.mesh ../../../../../../data/geom/orq/uniform_random.7.ascii 8 0.005 >> KDTree.domain.txt
