../../PlaceboCheck.exe ../../../../../../data/geom/orq/uniform_random.2.ascii 1 8 >> PlaceboCheck.txt
../../PlaceboCheck.exe ../../../../../../data/geom/orq/uniform_random.3.ascii 1 9 >> PlaceboCheck.txt
../../PlaceboCheck.exe ../../../../../../data/geom/orq/uniform_random.4.ascii 1 10 >> PlaceboCheck.txt
../../PlaceboCheck.exe ../../../../../../data/geom/orq/uniform_random.5.ascii 1 10 >> PlaceboCheck.txt
../../PlaceboCheck.exe ../../../../../../data/geom/orq/uniform_random.6.ascii 1 10 >> PlaceboCheck.txt
#../../PlaceboCheck.exe ../../../../../../data/geom/orq/uniform_random.7.ascii 1 10 >> PlaceboCheck.txt
