../../SequentialScan.exe ../../../../../../data/geom/orq/uniform_random.2.ascii 0.232079 >> SequentialScan.txt
../../SequentialScan.exe ../../../../../../data/geom/orq/uniform_random.3.ascii 0.107722 >> SequentialScan.txt
../../SequentialScan.exe ../../../../../../data/geom/orq/uniform_random.4.ascii 0.05 >> SequentialScan.txt
#../../SequentialScan.exe ../../../../../../data/geom/orq/uniform_random.5.ascii 0.0232079 >> SequentialScan.txt
#../../SequentialScan.exe ../../../../../../data/geom/orq/uniform_random.6.ascii 0.0107722 >> SequentialScan.txt
#../../SequentialScan.exe ../../../../../../data/geom/orq/uniform_random.7.ascii 0.005 >> SequentialScan.txt
